# Generated by Django 5.2 on 2025-07-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0002_contrato_costo_contrato_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/pdfs/'),
        ),
    ]
