# Generated by Django 5.2.4 on 2025-07-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionContratos', '0007_terminoscondiciones_fecha_modificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadUsuario',
        ),
    ]
